In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!kaggle datasets download -d stealthtechnologies/employee-attrition-dataset

Dataset URL: https://www.kaggle.com/datasets/stealthtechnologies/employee-attrition-dataset
License(s): apache-2.0
Downloading employee-attrition-dataset.zip to /content
  0% 0.00/1.72M [00:00<?, ?B/s]
100% 1.72M/1.72M [00:00<00:00, 84.9MB/s]

In [3]:
!unzip employee-attrition-dataset.zip

Archive:  employee-attrition-dataset.zip
  inflating: test.csv
  inflating: train.csv

In [4]:
df_train = pd.read_csv("train.csv")
df_train

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59593,37195,50,Female,12,Education,4414,Fair,High,Average,1,...,2,Senior,Small,35,No,No,Yes,Poor,Very High,Left
59594,6266,18,Male,4,Healthcare,8040,Fair,High,High,3,...,0,Senior,Medium,73,No,No,No,Fair,Medium,Left
59595,54887,22,Female,14,Technology,7944,Fair,High,High,0,...,2,Entry,Small,29,No,Yes,No,Good,Medium,Stayed
59596,861,23,Male,8,Education,2931,Fair,Very High,Average,0,...,0,Entry,Large,9,No,No,No,Good,Low,Left
59597,15796,56,Male,19,Technology,6660,Good,High,Average,0,...,3,Mid,Medium,81,No,No,No,Good,Low,Stayed

In [5]:
df_test = pd.read_csv("test.csv")
df_test

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,52685,36,Male,13,Healthcare,8029,Excellent,High,Average,1,...,1,Mid,Large,22,No,No,No,Poor,Medium,Stayed
1,30585,35,Male,7,Education,4563,Good,High,Average,1,...,4,Entry,Medium,27,No,No,No,Good,High,Left
2,54656,50,Male,7,Education,5583,Fair,High,Average,3,...,2,Senior,Medium,76,No,No,Yes,Good,Low,Stayed
3,33442,58,Male,44,Media,5525,Fair,Very High,High,0,...,4,Entry,Medium,96,No,No,No,Poor,Low,Left
4,15667,39,Male,24,Education,4604,Good,High,Average,0,...,6,Mid,Large,45,Yes,No,No,Good,High,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14895,16243,56,Female,42,Healthcare,7830,Poor,Medium,Average,0,...,0,Senior,Medium,60,No,No,No,Poor,Medium,Stayed
14896,47175,30,Female,15,Education,3856,Good,Medium,Average,2,...,0,Entry,Medium,20,No,No,No,Good,Medium,Left
14897,12409,52,Male,5,Education,5654,Good,Very High,Below Average,0,...,4,Mid,Small,7,No,No,No,Good,High,Left
14898,9554,18,Male,4,Education,5276,Fair,High,Average,0,...,3,Mid,Large,5,No,No,No,Poor,High,Stayed
14899,73042,59,Female,48,Education,3774,Good,High,Below Average,1,...,4,Mid,Large,118,No,No,No,Good,Very High,Left

In [6]:
df = pd.concat([df_train, df_test], ignore_index=True)
df

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74493,16243,56,Female,42,Healthcare,7830,Poor,Medium,Average,0,...,0,Senior,Medium,60,No,No,No,Poor,Medium,Stayed
74494,47175,30,Female,15,Education,3856,Good,Medium,Average,2,...,0,Entry,Medium,20,No,No,No,Good,Medium,Left
74495,12409,52,Male,5,Education,5654,Good,Very High,Below Average,0,...,4,Mid,Small,7,No,No,No,Good,High,Left
74496,9554,18,Male,4,Education,5276,Fair,High,Average,0,...,3,Mid,Large,5,No,No,No,Poor,High,Stayed
74497,73042,59,Female,48,Education,3774,Good,High,Below Average,1,...,4,Mid,Large,118,No,No,No,Good,Very High,Left

In [7]:
df.to_csv("attrition_data.csv")

In [ ]:
df.head(20)

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed
5,24368,38,Female,3,Technology,9977,Fair,High,Below Average,3,...,0,Mid,Medium,47,No,No,Yes,Fair,High,Left
6,64970,47,Male,23,Education,3681,Fair,High,High,1,...,3,Entry,Small,93,No,No,No,Good,Medium,Left
7,36999,48,Male,16,Finance,11223,Excellent,Very High,High,2,...,4,Entry,Medium,88,No,No,No,Excellent,Low,Stayed
8,32714,57,Male,44,Education,3773,Good,Medium,High,1,...,4,Entry,Medium,75,No,No,No,Fair,Medium,Stayed
9,15944,24,Female,1,Healthcare,7319,Poor,High,Average,1,...,4,Entry,Large,45,No,No,Yes,Good,Low,Left
10,29972,30,Female,12,Education,5443,Good,High,Average,1,...,1,Entry,Small,17,No,No,No,Good,Medium,Left
11,9063,29,Female,6,Healthcare,8950,Poor,Medium,Low,2,...,0,Mid,Medium,38,No,No,No,Poor,Medium,Left
12,21896,47,Female,38,Technology,9039,Fair,Very High,High,1,...,0,Entry,Small,68,No,No,No,Good,Low,Left
13,28098,31,Male,22,Healthcare,8090,Fair,Medium,High,4,...,2,Mid,Small,84,No,No,No,Good,Medium,Stayed
14,22068,40,Female,30,Technology,6350,Good,High,Average,0,...,0,Senior,Large,96,No,No,No,Good,High,Stayed
15,17696,40,Female,4,Finance,5176,Poor,High,Average,0,...,0,Entry,Small,21,Yes,No,No,Good,High,Left
16,55668,19,Female,9,Technology,8242,Excellent,Medium,Average,2,...,3,Mid,Small,63,No,No,No,Fair,High,Left
17,19288,33,Female,1,Finance,8733,Good,High,Below Average,1,...,0,Mid,Small,19,No,No,No,Good,Low,Stayed
18,17034,49,Female,37,Media,6252,Fair,High,High,2,...,4,Senior,Medium,70,No,No,No,Good,High,Stayed
19,9697,29,Male,9,Healthcare,7538,Fair,Medium,Average,0,...,0,Senior,Small,76,No,No,No,Good,High,Stayed

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74498 entries, 0 to 74497
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee ID               74498 non-null  int64
 1   Age                       74498 non-null  int64
 2   Gender                    74498 non-null  object
 3   Years at Company          74498 non-null  int64
 4   Job Role                  74498 non-null  object
 5   Monthly Income            74498 non-null  int64
 6   Work-Life Balance         74498 non-null  object
 7   Job Satisfaction          74498 non-null  object
 8   Performance Rating        74498 non-null  object
 9   Number of Promotions      74498 non-null  int64
 10  Overtime                  74498 non-null  object
 11  Distance from Home        74498 non-null  int64
 12  Education Level           74498 non-null  object
 13  Marital Status            74498 non-null  object
 14  Number of Dependents      74498 non-null  int64
 15  Job Level                 74498 non-null  object
 16  Company Size              74498 non-null  object
 17  Company Tenure            74498 non-null  int64
 18  Remote Work               74498 non-null  object
 19  Leadership Opportunities  74498 non-null  object
 20  Innovation Opportunities  74498 non-null  object
 21  Company Reputation        74498 non-null  object
 22  Employee Recognition      74498 non-null  object
 23  Attrition                 74498 non-null  object
dtypes: int64(8), object(16)
memory usage: 13.6+ MB

In [8]:
df.drop("Employee ID", axis = 1, inplace=True)

In [ ]:
df.describe()

,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure
count,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000
mean,38.529746,15.721603,7299.379514,0.832935,49.991584,1.650326,55.727456
std,12.083456,11.223744,2152.508566,0.995289,28.513611,1.553633,25.399349
min,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,28.000000,7.000000,5652.000000,0.000000,25.000000,0.000000,36.000000
50%,39.000000,13.000000,7348.000000,1.000000,50.000000,1.000000,56.000000
75%,49.000000,23.000000,8876.000000,2.000000,75.000000,3.000000,76.000000
max,59.000000,51.000000,16149.000000,4.000000,99.000000,6.000000,128.000000

In [9]:
cols = ["Years at Company", "Monthly Income", "Monthly Income", "Company Tenure"]
for col in cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  df = df[(df[col] >= (Q1 - 1.5 * IQR)) & (df[col] <= (Q3 + 1.5 * IQR))]

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74094 entries, 0 to 74496
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       74094 non-null  int64
 1   Gender                    74094 non-null  object
 2   Years at Company          74094 non-null  int64
 3   Job Role                  74094 non-null  object
 4   Monthly Income            74094 non-null  int64
 5   Work-Life Balance         74094 non-null  object
 6   Job Satisfaction          74094 non-null  object
 7   Performance Rating        74094 non-null  object
 8   Number of Promotions      74094 non-null  int64
 9   Overtime                  74094 non-null  object
 10  Distance from Home        74094 non-null  int64
 11  Education Level           74094 non-null  object
 12  Marital Status            74094 non-null  object
 13  Number of Dependents      74094 non-null  int64
 14  Job Level                 74094 non-null  object
 15  Company Size              74094 non-null  object
 16  Company Tenure            74094 non-null  int64
 17  Remote Work               74094 non-null  object
 18  Leadership Opportunities  74094 non-null  object
 19  Innovation Opportunities  74094 non-null  object
 20  Company Reputation        74094 non-null  object
 21  Employee Recognition      74094 non-null  object
 22  Attrition                 74094 non-null  object
dtypes: int64(7), object(16)
memory usage: 13.6+ MB

In [ ]:
df.describe()

,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure
count,74094.000000,74094.000000,74094.000000,74094.000000,74094.000000,74094.000000,74094.000000
mean,38.441561,15.570640,7293.502389,0.833023,50.001970,1.650633,55.571706
std,12.039470,11.022477,2143.602927,0.995314,28.519978,1.553782,25.312802
min,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,28.000000,7.000000,5651.000000,0.000000,25.000000,0.000000,36.000000
50%,38.000000,13.000000,7346.000000,1.000000,50.000000,1.000000,56.000000
75%,49.000000,23.000000,8871.000000,2.000000,75.000000,3.000000,75.000000
max,59.000000,47.000000,13699.000000,4.000000,99.000000,6.000000,126.000000

In [10]:
cols = list(df.columns)
for i in range(len(cols)):
  cols[i] = cols[i].replace(" ", '_')
  cols[i] = cols[i].replace("-", '_')
df.columns = cols
df.columns

Index(['Age', 'Gender', 'Years_at_Company', 'Job_Role', 'Monthly_Income',
       'Work_Life_Balance', 'Job_Satisfaction', 'Performance_Rating',
       'Number_of_Promotions', 'Overtime', 'Distance_from_Home',
       'Education_Level', 'Marital_Status', 'Number_of_Dependents',
       'Job_Level', 'Company_Size', 'Company_Tenure', 'Remote_Work',
       'Leadership_Opportunities', 'Innovation_Opportunities',
       'Company_Reputation', 'Employee_Recognition', 'Attrition'],
      dtype='object')

In [ ]:
df.head()

,Age,Gender,Years_at_Company,Job_Role,Monthly_Income,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Number_of_Promotions,Overtime,...,Number_of_Dependents,Job_Level,Company_Size,Company_Tenure,Remote_Work,Leadership_Opportunities,Innovation_Opportunities,Company_Reputation,Employee_Recognition,Attrition
0,31,Male,19,Education,5390,Excellent,Medium,Average,2,No,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,59,Female,4,Media,5534,Poor,High,Low,3,No,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,24,Female,10,Healthcare,8159,Good,High,Low,0,No,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,36,Female,7,Education,3989,Good,High,High,1,No,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,56,Male,41,Education,4821,Fair,Very High,Average,0,Yes,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

In [ ]:
for col in df.columns:
  if(df[col].dtype == object):
    print(df[col].value_counts())
    print("_______________________________")

Gender
Male      40612
Female    33482
Name: count, dtype: int64
_______________________________
Job_Role
Technology    19221
Healthcare    16995
Education     15589
Media         11933
Finance       10356
Name: count, dtype: int64
_______________________________
Work_Life_Balance
Good         28000
Fair         22415
Excellent    13355
Poor         10324
Name: count, dtype: int64
_______________________________
Job_Satisfaction
High         37038
Very High    14982
Medium       14649
Low           7425
Name: count, dtype: int64
_______________________________
Performance_Rating
Average          44457
High             14851
Below Average    11071
Low               3715
Name: count, dtype: int64
_______________________________
Overtime
No     49869
Yes    24225
Name: count, dtype: int64
_______________________________
Education_Level
Bachelor’s Degree    22203
Associate Degree     18554
Master’s Degree      14941
High School          14605
PhD                   3791
Name: count, dtype: int64
_______________________________
Marital_Status
Married     37217
Single      25865
Divorced    11012
Name: count, dtype: int64
_______________________________
Job_Level
Entry     29640
Mid       29505
Senior    14949
Name: count, dtype: int64
_______________________________
Company_Size
Medium    37041
Small     22218
Large     14835
Name: count, dtype: int64
_______________________________
Remote_Work
No     59964
Yes    14130
Name: count, dtype: int64
_______________________________
Leadership_Opportunities
No     70457
Yes     3637
Name: count, dtype: int64
_______________________________
Innovation_Opportunities
No     62056
Yes    12038
Name: count, dtype: int64
_______________________________
Company_Reputation
Good         36965
Poor         15039
Fair         14705
Excellent     7385
Name: count, dtype: int64
_______________________________
Employee_Recognition
Low          29464
Medium       22546
High         18438
Very High     3646
Name: count, dtype: int64
_______________________________
Attrition
Stayed    38894
Left      35200
Name: count, dtype: int64
_______________________________

In [11]:
encoding_map = {'Male':1, 'Female':0, 'Yes':1, 'No':0, 'Poor':1, 'Fair':2, 'Good':3, 'Excellent':4, 'Low':1, 'Medium':2, 'High':3, 'Very High':4, 'Low':0, 'Below Average':1, 'Average':2, 'High School':1, 'Associate Degree':2, 'Bachelor’s Degree':3, 'Master’s Degree':4, 'PhD':5, 'Entry':1, 'Mid':2, 'Senior':3, 'Small':1, 'Large':3, 'Stayed':1, 'Left':0}
for col in ['Gender', 'Work_Life_Balance', 'Job_Satisfaction', 'Performance_Rating',
       'Overtime', 'Education_Level', 'Job_Level', 'Company_Size', 'Remote_Work',
       'Leadership_Opportunities', 'Innovation_Opportunities',
       'Company_Reputation', 'Employee_Recognition', 'Attrition']:
  df[col] = df[col].map(encoding_map)

df

,Age,Gender,Years_at_Company,Job_Role,Monthly_Income,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Number_of_Promotions,Overtime,...,Number_of_Dependents,Job_Level,Company_Size,Company_Tenure,Remote_Work,Leadership_Opportunities,Innovation_Opportunities,Company_Reputation,Employee_Recognition,Attrition
0,31,1,19,Education,5390,4,2,2,2,0,...,0,2,2,89,0,0,0,4,2,1
1,59,0,4,Media,5534,1,3,0,3,0,...,3,2,2,21,0,0,0,2,0,1
2,24,0,10,Healthcare,8159,3,3,0,0,0,...,3,2,2,74,0,0,0,1,0,1
3,36,0,7,Education,3989,3,3,3,1,0,...,2,2,1,50,1,0,0,3,2,1
4,56,1,41,Education,4821,2,4,2,0,1,...,0,3,2,68,0,0,0,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74492,52,1,13,Technology,9296,1,3,2,1,1,...,1,1,1,55,0,1,0,1,0,1
74493,56,0,42,Healthcare,7830,1,2,2,0,1,...,0,3,2,60,0,0,0,1,2,1
74494,30,0,15,Education,3856,3,2,2,2,1,...,0,1,2,20,0,0,0,3,2,0
74495,52,1,5,Education,5654,3,4,1,0,0,...,4,2,1,7,0,0,0,3,3,0
74496,18,1,4,Education,5276,2,3,2,0,0,...,3,2,3,5,0,0,0,1,3,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74094 entries, 0 to 74496
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       74094 non-null  int64
 1   Gender                    74094 non-null  int64
 2   Years_at_Company          74094 non-null  int64
 3   Job_Role                  74094 non-null  object
 4   Monthly_Income            74094 non-null  int64
 5   Work_Life_Balance         74094 non-null  int64
 6   Job_Satisfaction          74094 non-null  int64
 7   Performance_Rating        74094 non-null  int64
 8   Number_of_Promotions      74094 non-null  int64
 9   Overtime                  74094 non-null  int64
 10  Distance_from_Home        74094 non-null  int64
 11  Education_Level           74094 non-null  int64
 12  Marital_Status            74094 non-null  object
 13  Number_of_Dependents      74094 non-null  int64
 14  Job_Level                 74094 non-null  int64
 15  Company_Size              74094 non-null  int64
 16  Company_Tenure            74094 non-null  int64
 17  Remote_Work               74094 non-null  int64
 18  Leadership_Opportunities  74094 non-null  int64
 19  Innovation_Opportunities  74094 non-null  int64
 20  Company_Reputation        74094 non-null  int64
 21  Employee_Recognition      74094 non-null  int64
 22  Attrition                 74094 non-null  int64
dtypes: int64(21), object(2)
memory usage: 13.6+ MB

In [12]:
df_encoded = pd.get_dummies(df, columns=["Marital_Status", "Job_Role"])
df_encoded.head()

,Age,Gender,Years_at_Company,Monthly_Income,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Number_of_Promotions,Overtime,Distance_from_Home,...,Employee_Recognition,Attrition,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single,Job_Role_Education,Job_Role_Finance,Job_Role_Healthcare,Job_Role_Media,Job_Role_Technology
0,31,1,19,5390,4,2,2,2,0,22,...,2,1,False,True,False,True,False,False,False,False
1,59,0,4,5534,1,3,0,3,0,21,...,0,1,True,False,False,False,False,False,True,False
2,24,0,10,8159,3,3,0,0,0,11,...,0,1,False,True,False,False,False,True,False,False
3,36,0,7,3989,3,3,3,1,0,27,...,2,1,False,False,True,True,False,False,False,False
4,56,1,41,4821,2,4,2,0,1,71,...,2,1,True,False,False,True,False,False,False,False

In [13]:
df_encoded.drop(["Job_Role_Technology", "Marital_Status_Single"], axis = 1, inplace=True)
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74094 entries, 0 to 74496
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       74094 non-null  int64
 1   Gender                    74094 non-null  int64
 2   Years_at_Company          74094 non-null  int64
 3   Monthly_Income            74094 non-null  int64
 4   Work_Life_Balance         74094 non-null  int64
 5   Job_Satisfaction          74094 non-null  int64
 6   Performance_Rating        74094 non-null  int64
 7   Number_of_Promotions      74094 non-null  int64
 8   Overtime                  74094 non-null  int64
 9   Distance_from_Home        74094 non-null  int64
 10  Education_Level           74094 non-null  int64
 11  Number_of_Dependents      74094 non-null  int64
 12  Job_Level                 74094 non-null  int64
 13  Company_Size              74094 non-null  int64
 14  Company_Tenure            74094 non-null  int64
 15  Remote_Work               74094 non-null  int64
 16  Leadership_Opportunities  74094 non-null  int64
 17  Innovation_Opportunities  74094 non-null  int64
 18  Company_Reputation        74094 non-null  int64
 19  Employee_Recognition      74094 non-null  int64
 20  Attrition                 74094 non-null  int64
 21  Marital_Status_Divorced   74094 non-null  bool
 22  Marital_Status_Married    74094 non-null  bool
 23  Job_Role_Education        74094 non-null  bool
 24  Job_Role_Finance          74094 non-null  bool
 25  Job_Role_Healthcare       74094 non-null  bool
 26  Job_Role_Media            74094 non-null  bool
dtypes: bool(6), int64(21)
memory usage: 12.9 MB

In [14]:
for col in df_encoded.columns:
  if df_encoded[col].dtype == bool:
    df_encoded[col] = df_encoded[col].astype(np.int64)

df_encoded

,Age,Gender,Years_at_Company,Monthly_Income,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Number_of_Promotions,Overtime,Distance_from_Home,...,Innovation_Opportunities,Company_Reputation,Employee_Recognition,Attrition,Marital_Status_Divorced,Marital_Status_Married,Job_Role_Education,Job_Role_Finance,Job_Role_Healthcare,Job_Role_Media
0,31,1,19,5390,4,2,2,2,0,22,...,0,4,2,1,0,1,1,0,0,0
1,59,0,4,5534,1,3,0,3,0,21,...,0,2,0,1,1,0,0,0,0,1
2,24,0,10,8159,3,3,0,0,0,11,...,0,1,0,1,0,1,0,0,1,0
3,36,0,7,3989,3,3,3,1,0,27,...,0,3,2,1,0,0,1,0,0,0
4,56,1,41,4821,2,4,2,0,1,71,...,0,2,2,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74492,52,1,13,9296,1,3,2,1,1,31,...,0,1,0,1,0,1,0,0,0,0
74493,56,0,42,7830,1,2,2,0,1,40,...,0,1,2,1,0,0,0,0,1,0
74494,30,0,15,3856,3,2,2,2,1,45,...,0,3,2,0,0,1,1,0,0,0
74495,52,1,5,5654,3,4,1,0,0,4,...,0,3,3,0,0,1,1,0,0,0
74496,18,1,4,5276,2,3,2,0,0,13,...,0,1,3,1,1,0,1,0,0,0

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74094 entries, 0 to 74496
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       74094 non-null  int64
 1   Gender                    74094 non-null  int64
 2   Years_at_Company          74094 non-null  int64
 3   Monthly_Income            74094 non-null  int64
 4   Work_Life_Balance         74094 non-null  int64
 5   Job_Satisfaction          74094 non-null  int64
 6   Performance_Rating        74094 non-null  int64
 7   Number_of_Promotions      74094 non-null  int64
 8   Overtime                  74094 non-null  int64
 9   Distance_from_Home        74094 non-null  int64
 10  Education_Level           74094 non-null  int64
 11  Number_of_Dependents      74094 non-null  int64
 12  Job_Level                 74094 non-null  int64
 13  Company_Size              74094 non-null  int64
 14  Company_Tenure            74094 non-null  int64
 15  Remote_Work               74094 non-null  int64
 16  Leadership_Opportunities  74094 non-null  int64
 17  Innovation_Opportunities  74094 non-null  int64
 18  Company_Reputation        74094 non-null  int64
 19  Employee_Recognition      74094 non-null  int64
 20  Attrition                 74094 non-null  int64
 21  Marital_Status_Divorced   74094 non-null  int64
 22  Marital_Status_Married    74094 non-null  int64
 23  Job_Role_Education        74094 non-null  int64
 24  Job_Role_Finance          74094 non-null  int64
 25  Job_Role_Healthcare       74094 non-null  int64
 26  Job_Role_Media            74094 non-null  int64
dtypes: int64(27)
memory usage: 15.8 MB

In [15]:

X_tot = np.array(df_encoded.drop("Attrition", axis = 1))
y_tot = np.array(df_encoded["Attrition"])
print(X_tot.shape)
print(y_tot.shape)

(74094, 26)
(74094,)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X_tot, y_tot, test_size=0.2, random_state=42, shuffle=True)

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
import pickle

# save the iris classification model as a pickle file
model_pkl_file = "Standard_Scaler.pkl"

with open(model_pkl_file, 'wb') as file:
    pickle.dump(scaler, file)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.71      0.72      7130
           1       0.74      0.76      0.75      7689

    accuracy                           0.74     14819
   macro avg       0.74      0.74      0.74     14819
weighted avg       0.74      0.74      0.74     14819

In [20]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.73      0.74      7130
           1       0.76      0.76      0.76      7689

    accuracy                           0.75     14819
   macro avg       0.75      0.75      0.75     14819
weighted avg       0.75      0.75      0.75     14819

In [21]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(11)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.68      0.68      7130
           1       0.71      0.72      0.71      7689

    accuracy                           0.70     14819
   macro avg       0.70      0.70      0.70     14819
weighted avg       0.70      0.70      0.70     14819

In [22]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=9)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.75      0.73      7130
           1       0.76      0.72      0.74      7689

    accuracy                           0.74     14819
   macro avg       0.74      0.74      0.74     14819
weighted avg       0.74      0.74      0.74     14819

In [23]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=12)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.73      0.74      7130
           1       0.76      0.77      0.76      7689

    accuracy                           0.75     14819
   macro avg       0.75      0.75      0.75     14819
weighted avg       0.75      0.75      0.75     14819

In [20]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.74      0.75      7130
           1       0.77      0.78      0.77      7689

    accuracy                           0.76     14819
   macro avg       0.76      0.76      0.76     14819
weighted avg       0.76      0.76      0.76     14819

In [22]:


# save the iris classification model as a pickle file
model_pkl_file = "GradientBoostingClassifier.pkl"

with open(model_pkl_file, 'wb') as file:
    pickle.dump(model, file)

In [26]:
from joblib import dump, load
dump(model, 'gradient_boosting_model.joblib')

['gradient_boosting_model.joblib']

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.5-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (2.1.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.5-cp310-cp310-manylinux2014_x86_64.whl (98.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 MB 6.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.5

In [ ]:
from catboost import CatBoostClassifier, Pool
model = CatBoostClassifier()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Learning rate set to 0.058878
0:	learn: 0.6703182	total: 19.5ms	remaining: 19.5s
1:	learn: 0.6509404	total: 36.6ms	remaining: 18.2s
2:	learn: 0.6345042	total: 54.8ms	remaining: 18.2s
3:	learn: 0.6205013	total: 72.3ms	remaining: 18s
4:	learn: 0.6090727	total: 90.2ms	remaining: 17.9s
5:	learn: 0.5998515	total: 109ms	remaining: 18s
6:	learn: 0.5903443	total: 126ms	remaining: 17.8s
7:	learn: 0.5826421	total: 142ms	remaining: 17.6s
8:	learn: 0.5760729	total: 160ms	remaining: 17.6s
9:	learn: 0.5696358	total: 176ms	remaining: 17.4s
10:	learn: 0.5651534	total: 196ms	remaining: 17.6s
11:	learn: 0.5593721	total: 212ms	remaining: 17.4s
12:	learn: 0.5554860	total: 228ms	remaining: 17.3s
13:	learn: 0.5509145	total: 244ms	remaining: 17.2s
14:	learn: 0.5474326	total: 261ms	remaining: 17.2s
15:	learn: 0.5442223	total: 278ms	remaining: 17.1s
16:	learn: 0.5401505	total: 297ms	remaining: 17.2s
17:	learn: 0.5372544	total: 318ms	remaining: 17.4s
18:	learn: 0.5349095	total: 336ms	remaining: 17.3s
19:	learn: 0.5319695	total: 351ms	remaining: 17.2s
20:	learn: 0.5297046	total: 368ms	remaining: 17.1s
21:	learn: 0.5271033	total: 384ms	remaining: 17.1s
22:	learn: 0.5241815	total: 403ms	remaining: 17.1s
23:	learn: 0.5217918	total: 421ms	remaining: 17.1s
24:	learn: 0.5201237	total: 437ms	remaining: 17s
25:	learn: 0.5184955	total: 452ms	remaining: 16.9s
26:	learn: 0.5169156	total: 469ms	remaining: 16.9s
27:	learn: 0.5147273	total: 485ms	remaining: 16.8s
28:	learn: 0.5131342	total: 502ms	remaining: 16.8s
29:	learn: 0.5117833	total: 518ms	remaining: 16.7s
30:	learn: 0.5103816	total: 534ms	remaining: 16.7s
31:	learn: 0.5091715	total: 550ms	remaining: 16.6s
32:	learn: 0.5078192	total: 566ms	remaining: 16.6s
33:	learn: 0.5062394	total: 582ms	remaining: 16.5s
34:	learn: 0.5050043	total: 599ms	remaining: 16.5s
35:	learn: 0.5038226	total: 619ms	remaining: 16.6s
36:	learn: 0.5027984	total: 635ms	remaining: 16.5s
37:	learn: 0.5013276	total: 651ms	remaining: 16.5s
38:	learn: 0.5001978	total: 668ms	remaining: 16.5s
39:	learn: 0.4992952	total: 686ms	remaining: 16.5s
40:	learn: 0.4984497	total: 703ms	remaining: 16.4s
41:	learn: 0.4969981	total: 720ms	remaining: 16.4s
42:	learn: 0.4961369	total: 735ms	remaining: 16.4s
43:	learn: 0.4952489	total: 751ms	remaining: 16.3s
44:	learn: 0.4940737	total: 768ms	remaining: 16.3s
45:	learn: 0.4933354	total: 784ms	remaining: 16.3s
46:	learn: 0.4924447	total: 799ms	remaining: 16.2s
47:	learn: 0.4917420	total: 814ms	remaining: 16.1s
48:	learn: 0.4908810	total: 833ms	remaining: 16.2s
49:	learn: 0.4902128	total: 848ms	remaining: 16.1s
50:	learn: 0.4896273	total: 864ms	remaining: 16.1s
51:	learn: 0.4890019	total: 884ms	remaining: 16.1s
52:	learn: 0.4881111	total: 906ms	remaining: 16.2s
53:	learn: 0.4873320	total: 924ms	remaining: 16.2s
54:	learn: 0.4867544	total: 952ms	remaining: 16.4s
55:	learn: 0.4860850	total: 978ms	remaining: 16.5s
56:	learn: 0.4855862	total: 1000ms	remaining: 16.5s
57:	learn: 0.4851244	total: 1.02s	remaining: 16.5s
58:	learn: 0.4845987	total: 1.04s	remaining: 16.6s
59:	learn: 0.4841484	total: 1.06s	remaining: 16.5s
60:	learn: 0.4836146	total: 1.07s	remaining: 16.5s
61:	learn: 0.4831864	total: 1.09s	remaining: 16.5s
62:	learn: 0.4825882	total: 1.11s	remaining: 16.5s
63:	learn: 0.4821083	total: 1.12s	remaining: 16.4s
64:	learn: 0.4816926	total: 1.14s	remaining: 16.5s
65:	learn: 0.4812152	total: 1.16s	remaining: 16.4s
66:	learn: 0.4808121	total: 1.18s	remaining: 16.4s
67:	learn: 0.4803616	total: 1.19s	remaining: 16.4s
68:	learn: 0.4799367	total: 1.21s	remaining: 16.3s
69:	learn: 0.4795201	total: 1.22s	remaining: 16.3s
70:	learn: 0.4791038	total: 1.24s	remaining: 16.3s
71:	learn: 0.4786172	total: 1.26s	remaining: 16.2s
72:	learn: 0.4782404	total: 1.27s	remaining: 16.2s
73:	learn: 0.4779330	total: 1.29s	remaining: 16.2s
74:	learn: 0.4775907	total: 1.31s	remaining: 16.1s
75:	learn: 0.4770755	total: 1.33s	remaining: 16.1s
76:	learn: 0.4766090	total: 1.35s	remaining: 16.1s
77:	learn: 0.4762281	total: 1.36s	remaining: 16.1s
78:	learn: 0.4759298	total: 1.38s	remaining: 16.1s
79:	learn: 0.4755843	total: 1.39s	remaining: 16s
80:	learn: 0.4753169	total: 1.41s	remaining: 16s
81:	learn: 0.4749987	total: 1.43s	remaining: 16s
82:	learn: 0.4746609	total: 1.44s	remaining: 16s
83:	learn: 0.4744210	total: 1.46s	remaining: 15.9s
84:	learn: 0.4742161	total: 1.48s	remaining: 15.9s
85:	learn: 0.4739906	total: 1.5s	remaining: 15.9s
86:	learn: 0.4738084	total: 1.51s	remaining: 15.9s
87:	learn: 0.4735713	total: 1.53s	remaining: 15.8s
88:	learn: 0.4731868	total: 1.54s	remaining: 15.8s
89:	learn: 0.4729471	total: 1.56s	remaining: 15.8s
90:	learn: 0.4726387	total: 1.58s	remaining: 15.7s
91:	learn: 0.4724023	total: 1.59s	remaining: 15.7s
92:	learn: 0.4721236	total: 1.61s	remaining: 15.7s
93:	learn: 0.4718730	total: 1.62s	remaining: 15.6s
94:	learn: 0.4717025	total: 1.64s	remaining: 15.6s
95:	learn: 0.4715142	total: 1.66s	remaining: 15.6s
96:	learn: 0.4713100	total: 1.67s	remaining: 15.6s
97:	learn: 0.4711267	total: 1.69s	remaining: 15.6s
98:	learn: 0.4708604	total: 1.71s	remaining: 15.5s
99:	learn: 0.4706906	total: 1.72s	remaining: 15.5s
100:	learn: 0.4704903	total: 1.74s	remaining: 15.5s
101:	learn: 0.4703070	total: 1.75s	remaining: 15.4s
102:	learn: 0.4701205	total: 1.77s	remaining: 15.4s
103:	learn: 0.4699666	total: 1.78s	remaining: 15.4s
104:	learn: 0.4697903	total: 1.8s	remaining: 15.3s
105:	learn: 0.4695774	total: 1.81s	remaining: 15.3s
106:	learn: 0.4694186	total: 1.83s	remaining: 15.3s
107:	learn: 0.4692764	total: 1.85s	remaining: 15.3s
108:	learn: 0.4691028	total: 1.87s	remaining: 15.3s
109:	learn: 0.4688974	total: 1.89s	remaining: 15.3s
110:	learn: 0.4687036	total: 1.9s	remaining: 15.2s
111:	learn: 0.4685472	total: 1.92s	remaining: 15.2s
112:	learn: 0.4683806	total: 1.94s	remaining: 15.2s
113:	learn: 0.4682545	total: 1.97s	remaining: 15.3s
114:	learn: 0.4681111	total: 1.99s	remaining: 15.3s
115:	learn: 0.4680151	total: 2.01s	remaining: 15.3s
116:	learn: 0.4678578	total: 2.02s	remaining: 15.3s
117:	learn: 0.4676655	total: 2.04s	remaining: 15.3s
118:	learn: 0.4675654	total: 2.06s	remaining: 15.2s
119:	learn: 0.4674318	total: 2.08s	remaining: 15.2s
120:	learn: 0.4672682	total: 2.09s	remaining: 15.2s
121:	learn: 0.4671896	total: 2.11s	remaining: 15.2s
122:	learn: 0.4670015	total: 2.12s	remaining: 15.1s
123:	learn: 0.4668894	total: 2.14s	remaining: 15.1s
124:	learn: 0.4667701	total: 2.16s	remaining: 15.1s
125:	learn: 0.4666461	total: 2.17s	remaining: 15.1s
126:	learn: 0.4664981	total: 2.19s	remaining: 15s
127:	learn: 0.4663712	total: 2.2s	remaining: 15s
128:	learn: 0.4662629	total: 2.22s	remaining: 15s
129:	learn: 0.4661350	total: 2.23s	remaining: 15s
130:	learn: 0.4659743	total: 2.25s	remaining: 14.9s
131:	learn: 0.4658663	total: 2.27s	remaining: 14.9s
132:	learn: 0.4657530	total: 2.29s	remaining: 14.9s
133:	learn: 0.4656034	total: 2.3s	remaining: 14.9s
134:	learn: 0.4654640	total: 2.32s	remaining: 14.9s
135:	learn: 0.4653188	total: 2.34s	remaining: 14.8s
136:	learn: 0.4651985	total: 2.35s	remaining: 14.8s
137:	learn: 0.4650628	total: 2.37s	remaining: 14.8s
138:	learn: 0.4649512	total: 2.38s	remaining: 14.8s
139:	learn: 0.4648428	total: 2.4s	remaining: 14.8s
140:	learn: 0.4647102	total: 2.42s	remaining: 14.7s
141:	learn: 0.4646137	total: 2.43s	remaining: 14.7s
142:	learn: 0.4645288	total: 2.45s	remaining: 14.7s
143:	learn: 0.4644034	total: 2.47s	remaining: 14.7s
144:	learn: 0.4642989	total: 2.49s	remaining: 14.7s
145:	learn: 0.4642131	total: 2.5s	remaining: 14.6s
146:	learn: 0.4640874	total: 2.52s	remaining: 14.6s
147:	learn: 0.4639593	total: 2.53s	remaining: 14.6s
148:	learn: 0.4638774	total: 2.55s	remaining: 14.6s
149:	learn: 0.4637980	total: 2.56s	remaining: 14.5s
150:	learn: 0.4636821	total: 2.58s	remaining: 14.5s
151:	learn: 0.4635928	total: 2.6s	remaining: 14.5s
152:	learn: 0.4634976	total: 2.61s	remaining: 14.5s
153:	learn: 0.4633970	total: 2.63s	remaining: 14.4s
154:	learn: 0.4632647	total: 2.64s	remaining: 14.4s
155:	learn: 0.4631926	total: 2.66s	remaining: 14.4s
156:	learn: 0.4630838	total: 2.67s	remaining: 14.4s
157:	learn: 0.4629578	total: 2.69s	remaining: 14.3s
158:	learn: 0.4628578	total: 2.71s	remaining: 14.3s
159:	learn: 0.4627564	total: 2.73s	remaining: 14.3s
160:	learn: 0.4626612	total: 2.74s	remaining: 14.3s
161:	learn: 0.4625684	total: 2.76s	remaining: 14.3s
162:	learn: 0.4624835	total: 2.77s	remaining: 14.2s
163:	learn: 0.4623907	total: 2.79s	remaining: 14.2s
164:	learn: 0.4622963	total: 2.8s	remaining: 14.2s
165:	learn: 0.4621958	total: 2.82s	remaining: 14.2s
166:	learn: 0.4621226	total: 2.83s	remaining: 14.1s
167:	learn: 0.4620370	total: 2.85s	remaining: 14.1s
168:	learn: 0.4619177	total: 2.87s	remaining: 14.1s
169:	learn: 0.4618235	total: 2.89s	remaining: 14.1s
170:	learn: 0.4617259	total: 2.91s	remaining: 14.1s
171:	learn: 0.4616191	total: 2.93s	remaining: 14.1s
172:	learn: 0.4615221	total: 2.95s	remaining: 14.1s
173:	learn: 0.4614318	total: 2.97s	remaining: 14.1s
174:	learn: 0.4613475	total: 3s	remaining: 14.1s
175:	learn: 0.4612659	total: 3.02s	remaining: 14.1s
176:	learn: 0.4611693	total: 3.03s	remaining: 14.1s
177:	learn: 0.4610681	total: 3.05s	remaining: 14.1s
178:	learn: 0.4609705	total: 3.07s	remaining: 14.1s
179:	learn: 0.4608899	total: 3.08s	remaining: 14s
180:	learn: 0.4608045	total: 3.1s	remaining: 14s
181:	learn: 0.4607310	total: 3.12s	remaining: 14s
182:	learn: 0.4606464	total: 3.14s	remaining: 14s
183:	learn: 0.4605822	total: 3.15s	remaining: 14s
184:	learn: 0.4604934	total: 3.17s	remaining: 14s
185:	learn: 0.4603919	total: 3.18s	remaining: 13.9s
186:	learn: 0.4603071	total: 3.2s	remaining: 13.9s
187:	learn: 0.4602368	total: 3.21s	remaining: 13.9s
188:	learn: 0.4601359	total: 3.23s	remaining: 13.9s
189:	learn: 0.4600423	total: 3.25s	remaining: 13.8s
190:	learn: 0.4599339	total: 3.26s	remaining: 13.8s
191:	learn: 0.4598403	total: 3.28s	remaining: 13.8s
192:	learn: 0.4597274	total: 3.3s	remaining: 13.8s
193:	learn: 0.4596548	total: 3.31s	remaining: 13.8s
194:	learn: 0.4595751	total: 3.33s	remaining: 13.7s
195:	learn: 0.4594904	total: 3.35s	remaining: 13.7s
196:	learn: 0.4594129	total: 3.36s	remaining: 13.7s
197:	learn: 0.4593159	total: 3.38s	remaining: 13.7s
198:	learn: 0.4592151	total: 3.39s	remaining: 13.7s
199:	learn: 0.4591263	total: 3.41s	remaining: 13.6s
200:	learn: 0.4590248	total: 3.42s	remaining: 13.6s
201:	learn: 0.4589399	total: 3.44s	remaining: 13.6s
202:	learn: 0.4588592	total: 3.46s	remaining: 13.6s
203:	learn: 0.4587768	total: 3.47s	remaining: 13.6s
204:	learn: 0.4586891	total: 3.49s	remaining: 13.5s
205:	learn: 0.4585807	total: 3.5s	remaining: 13.5s
206:	learn: 0.4584730	total: 3.52s	remaining: 13.5s
207:	learn: 0.4583854	total: 3.54s	remaining: 13.5s
208:	learn: 0.4583034	total: 3.56s	remaining: 13.5s
209:	learn: 0.4582164	total: 3.58s	remaining: 13.4s
210:	learn: 0.4581303	total: 3.59s	remaining: 13.4s
211:	learn: 0.4580417	total: 3.6s	remaining: 13.4s
212:	learn: 0.4579536	total: 3.62s	remaining: 13.4s
213:	learn: 0.4578698	total: 3.64s	remaining: 13.4s
214:	learn: 0.4577701	total: 3.65s	remaining: 13.3s
215:	learn: 0.4576676	total: 3.67s	remaining: 13.3s
216:	learn: 0.4575859	total: 3.68s	remaining: 13.3s
217:	learn: 0.4575113	total: 3.7s	remaining: 13.3s
218:	learn: 0.4574050	total: 3.72s	remaining: 13.3s
219:	learn: 0.4573174	total: 3.74s	remaining: 13.3s
220:	learn: 0.4572241	total: 3.76s	remaining: 13.3s
221:	learn: 0.4571267	total: 3.77s	remaining: 13.2s
222:	learn: 0.4570346	total: 3.8s	remaining: 13.2s
223:	learn: 0.4569337	total: 3.84s	remaining: 13.3s
224:	learn: 0.4568491	total: 3.87s	remaining: 13.3s
225:	learn: 0.4567508	total: 3.89s	remaining: 13.3s
226:	learn: 0.4566384	total: 3.92s	remaining: 13.4s
227:	learn: 0.4565632	total: 3.95s	remaining: 13.4s
228:	learn: 0.4564764	total: 4s	remaining: 13.5s
229:	learn: 0.4564115	total: 4.04s	remaining: 13.5s
230:	learn: 0.4563179	total: 4.06s	remaining: 13.5s
231:	learn: 0.4562404	total: 4.08s	remaining: 13.5s
232:	learn: 0.4561472	total: 4.11s	remaining: 13.5s
233:	learn: 0.4560537	total: 4.13s	remaining: 13.5s
234:	learn: 0.4559636	total: 4.16s	remaining: 13.5s
235:	learn: 0.4558810	total: 4.17s	remaining: 13.5s
236:	learn: 0.4557866	total: 4.21s	remaining: 13.5s
237:	learn: 0.4556991	total: 4.25s	remaining: 13.6s
238:	learn: 0.4555929	total: 4.27s	remaining: 13.6s
239:	learn: 0.4555188	total: 4.29s	remaining: 13.6s
240:	learn: 0.4554147	total: 4.31s	remaining: 13.6s
241:	learn: 0.4553128	total: 4.33s	remaining: 13.6s
242:	learn: 0.4552296	total: 4.37s	remaining: 13.6s
243:	learn: 0.4551486	total: 4.4s	remaining: 13.6s
244:	learn: 0.4550275	total: 4.44s	remaining: 13.7s
245:	learn: 0.4549625	total: 4.48s	remaining: 13.7s
246:	learn: 0.4548732	total: 4.52s	remaining: 13.8s
247:	learn: 0.4547916	total: 4.57s	remaining: 13.8s
248:	learn: 0.4547140	total: 4.61s	remaining: 13.9s
249:	learn: 0.4546386	total: 4.66s	remaining: 14s
250:	learn: 0.4545559	total: 4.7s	remaining: 14s
251:	learn: 0.4544925	total: 4.75s	remaining: 14.1s
252:	learn: 0.4544137	total: 4.79s	remaining: 14.1s
253:	learn: 0.4543177	total: 4.83s	remaining: 14.2s
254:	learn: 0.4542236	total: 4.88s	remaining: 14.3s
255:	learn: 0.4541486	total: 4.93s	remaining: 14.3s
256:	learn: 0.4540836	total: 4.96s	remaining: 14.3s
257:	learn: 0.4539988	total: 4.99s	remaining: 14.4s
258:	learn: 0.4539151	total: 5.02s	remaining: 14.4s
259:	learn: 0.4538261	total: 5.04s	remaining: 14.3s
260:	learn: 0.4537683	total: 5.07s	remaining: 14.4s
261:	learn: 0.4536733	total: 5.1s	remaining: 14.4s
262:	learn: 0.4535995	total: 5.12s	remaining: 14.4s
263:	learn: 0.4535076	total: 5.14s	remaining: 14.3s
264:	learn: 0.4534258	total: 5.16s	remaining: 14.3s
265:	learn: 0.4533370	total: 5.18s	remaining: 14.3s
266:	learn: 0.4532484	total: 5.23s	remaining: 14.4s
267:	learn: 0.4531601	total: 5.27s	remaining: 14.4s
268:	learn: 0.4530609	total: 5.32s	remaining: 14.5s
269:	learn: 0.4529581	total: 5.37s	remaining: 14.5s
270:	learn: 0.4528913	total: 5.41s	remaining: 14.5s
271:	learn: 0.4528128	total: 5.45s	remaining: 14.6s
272:	learn: 0.4527600	total: 5.49s	remaining: 14.6s
273:	learn: 0.4526887	total: 5.53s	remaining: 14.7s
274:	learn: 0.4526083	total: 5.57s	remaining: 14.7s
275:	learn: 0.4525263	total: 5.59s	remaining: 14.7s
276:	learn: 0.4524520	total: 5.62s	remaining: 14.7s
277:	learn: 0.4523601	total: 5.67s	remaining: 14.7s
278:	learn: 0.4522702	total: 5.7s	remaining: 14.7s
279:	learn: 0.4521893	total: 5.72s	remaining: 14.7s
280:	learn: 0.4521326	total: 5.76s	remaining: 14.7s
281:	learn: 0.4520700	total: 5.81s	remaining: 14.8s
282:	learn: 0.4519717	total: 5.84s	remaining: 14.8s
283:	learn: 0.4518857	total: 5.87s	remaining: 14.8s
284:	learn: 0.4518073	total: 5.91s	remaining: 14.8s
285:	learn: 0.4517361	total: 5.96s	remaining: 14.9s
286:	learn: 0.4516652	total: 5.98s	remaining: 14.9s
287:	learn: 0.4515880	total: 6.01s	remaining: 14.8s
288:	learn: 0.4515015	total: 6.05s	remaining: 14.9s
289:	learn: 0.4514234	total: 6.09s	remaining: 14.9s
290:	learn: 0.4513507	total: 6.14s	remaining: 15s
291:	learn: 0.4512713	total: 6.18s	remaining: 15s
292:	learn: 0.4511995	total: 6.22s	remaining: 15s
293:	learn: 0.4511092	total: 6.25s	remaining: 15s
294:	learn: 0.4510424	total: 6.29s	remaining: 15s
295:	learn: 0.4509401	total: 6.33s	remaining: 15.1s
296:	learn: 0.4508465	total: 6.35s	remaining: 15s
297:	learn: 0.4507661	total: 6.39s	remaining: 15.1s
298:	learn: 0.4506978	total: 6.43s	remaining: 15.1s
299:	learn: 0.4506202	total: 6.46s	remaining: 15.1s
300:	learn: 0.4505517	total: 6.49s	remaining: 15.1s
301:	learn: 0.4504867	total: 6.51s	remaining: 15s
302:	learn: 0.4504162	total: 6.54s	remaining: 15s
303:	learn: 0.4503097	total: 6.56s	remaining: 15s
304:	learn: 0.4502160	total: 6.58s	remaining: 15s
305:	learn: 0.4501472	total: 6.61s	remaining: 15s
306:	learn: 0.4500744	total: 6.63s	remaining: 15s
307:	learn: 0.4500027	total: 6.66s	remaining: 15s
308:	learn: 0.4499047	total: 6.71s	remaining: 15s
309:	learn: 0.4498195	total: 6.75s	remaining: 15s
310:	learn: 0.4497515	total: 6.79s	remaining: 15.1s
311:	learn: 0.4496721	total: 6.84s	remaining: 15.1s
312:	learn: 0.4495826	total: 6.89s	remaining: 15.1s
313:	learn: 0.4495352	total: 6.93s	remaining: 15.1s
314:	learn: 0.4494430	total: 6.97s	remaining: 15.2s
315:	learn: 0.4493885	total: 7.02s	remaining: 15.2s
316:	learn: 0.4493019	total: 7.07s	remaining: 15.2s
317:	learn: 0.4492153	total: 7.11s	remaining: 15.2s
318:	learn: 0.4491579	total: 7.15s	remaining: 15.3s
319:	learn: 0.4490578	total: 7.2s	remaining: 15.3s
320:	learn: 0.4489700	total: 7.24s	remaining: 15.3s
321:	learn: 0.4488912	total: 7.29s	remaining: 15.3s
322:	learn: 0.4488048	total: 7.33s	remaining: 15.4s
323:	learn: 0.4487491	total: 7.37s	remaining: 15.4s
324:	learn: 0.4486527	total: 7.41s	remaining: 15.4s
325:	learn: 0.4485642	total: 7.46s	remaining: 15.4s
326:	learn: 0.4484989	total: 7.51s	remaining: 15.4s
327:	learn: 0.4484223	total: 7.55s	remaining: 15.5s
328:	learn: 0.4483300	total: 7.59s	remaining: 15.5s
329:	learn: 0.4482430	total: 7.64s	remaining: 15.5s
330:	learn: 0.4481478	total: 7.67s	remaining: 15.5s
331:	learn: 0.4480778	total: 7.72s	remaining: 15.5s
332:	learn: 0.4479941	total: 7.75s	remaining: 15.5s
333:	learn: 0.4479160	total: 7.79s	remaining: 15.5s
334:	learn: 0.4478437	total: 7.83s	remaining: 15.5s
335:	learn: 0.4477650	total: 7.87s	remaining: 15.5s
336:	learn: 0.4476814	total: 7.91s	remaining: 15.6s
337:	learn: 0.4476186	total: 7.96s	remaining: 15.6s
338:	learn: 0.4475350	total: 7.97s	remaining: 15.5s
339:	learn: 0.4474824	total: 7.99s	remaining: 15.5s
340:	learn: 0.4474039	total: 8s	remaining: 15.5s
341:	learn: 0.4473288	total: 8.02s	remaining: 15.4s
342:	learn: 0.4472496	total: 8.04s	remaining: 15.4s
343:	learn: 0.4471895	total: 8.05s	remaining: 15.4s
344:	learn: 0.4471139	total: 8.07s	remaining: 15.3s
345:	learn: 0.4470502	total: 8.08s	remaining: 15.3s
346:	learn: 0.4469947	total: 8.1s	remaining: 15.2s
347:	learn: 0.4469106	total: 8.12s	remaining: 15.2s
348:	learn: 0.4468449	total: 8.13s	remaining: 15.2s
349:	learn: 0.4468029	total: 8.15s	remaining: 15.1s
350:	learn: 0.4467162	total: 8.18s	remaining: 15.1s
351:	learn: 0.4466316	total: 8.2s	remaining: 15.1s
352:	learn: 0.4465408	total: 8.21s	remaining: 15.1s
353:	learn: 0.4464394	total: 8.23s	remaining: 15s
354:	learn: 0.4463510	total: 8.25s	remaining: 15s
355:	learn: 0.4462637	total: 8.26s	remaining: 14.9s
356:	learn: 0.4461813	total: 8.28s	remaining: 14.9s
357:	learn: 0.4461403	total: 8.3s	remaining: 14.9s
358:	learn: 0.4460793	total: 8.31s	remaining: 14.8s
359:	learn: 0.4459946	total: 8.33s	remaining: 14.8s
360:	learn: 0.4459183	total: 8.34s	remaining: 14.8s
361:	learn: 0.4458370	total: 8.36s	remaining: 14.7s
362:	learn: 0.4457808	total: 8.38s	remaining: 14.7s
363:	learn: 0.4457141	total: 8.4s	remaining: 14.7s
364:	learn: 0.4456308	total: 8.42s	remaining: 14.6s
365:	learn: 0.4455444	total: 8.43s	remaining: 14.6s
366:	learn: 0.4454731	total: 8.45s	remaining: 14.6s
367:	learn: 0.4453987	total: 8.47s	remaining: 14.5s
368:	learn: 0.4453243	total: 8.48s	remaining: 14.5s
369:	learn: 0.4452303	total: 8.5s	remaining: 14.5s
370:	learn: 0.4451492	total: 8.51s	remaining: 14.4s
371:	learn: 0.4450571	total: 8.53s	remaining: 14.4s
372:	learn: 0.4449837	total: 8.54s	remaining: 14.4s
373:	learn: 0.4449149	total: 8.56s	remaining: 14.3s
374:	learn: 0.4448279	total: 8.58s	remaining: 14.3s
375:	learn: 0.4447523	total: 8.6s	remaining: 14.3s
376:	learn: 0.4446653	total: 8.61s	remaining: 14.2s
377:	learn: 0.4446029	total: 8.63s	remaining: 14.2s
378:	learn: 0.4445375	total: 8.64s	remaining: 14.2s
379:	learn: 0.4444839	total: 8.66s	remaining: 14.1s
380:	learn: 0.4444126	total: 8.67s	remaining: 14.1s
381:	learn: 0.4443684	total: 8.69s	remaining: 14.1s
382:	learn: 0.4443092	total: 8.71s	remaining: 14s
383:	learn: 0.4442394	total: 8.72s	remaining: 14s
384:	learn: 0.4441876	total: 8.74s	remaining: 14s
385:	learn: 0.4441232	total: 8.76s	remaining: 13.9s
386:	learn: 0.4440746	total: 8.78s	remaining: 13.9s
387:	learn: 0.4439790	total: 8.79s	remaining: 13.9s